import pygame
import os

SPRITESHEET_PATH = "pygame-assets\\img"

SCREEN_WIDTH, SCREEN_HEIGHT = 960,540
TILE_SIZE = 16

ANIMSPEED_HERO_DEFAULT = 0.25
ANIMSPEED_HERO_IDLE = 0.1


ANIMSPEED_BEE = 0.2
SPEED_BEE = 2
